name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  FORCE_COLOR: 1  # Enables colored output in shfmt & others

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: ShellCheck
        run: make lint-scripts

      - name: shfmt check
        uses: JeromeDev/shfmt-action@v2
        with:
          args: "--diff --exclude vendor --exclude .git"

      - name: Rubocop
        run: bundle exec rubocop

  integration-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        stack: ["heroku-20", "heroku-22", "heroku-24"]
    env:
      HATCHET_APP_LIMIT: 300
      HATCHET_DEFAULT_STACK: ${{ matrix.stack }}
      HATCHET_EXPENSIVE_MODE: 1
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_API_USER: ${{ secrets.HEROKU_API_USER }}
      HEROKU_DISABLE_AUTOUPDATE: 1
      PARALLEL_SPLIT_TEST_PROCESSES: 75
      RSPEC_RETRY_RETRY_COUNT: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Hatchet setup
        run: bundle exec hatchet ci:setup

      - name: Run Hatchet integration tests
        run: bundle exec parallel_split_test spec/hatchet/

  container-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run buildpack using default app fixture
        run: make run

      - name: Run buildpack with known failure fixture
        run: |
          make run \
            FIXTURE=spec/fixtures/python_version_file_invalid_version/ \
            COMPILE_FAILURE_EXIT_CODE=0